language: node_js
node_js:
- 7.8

before_script:
- pip install mbutil --user
- npm run build-tile
- npm run build

script:
- cat tiles/metadata.json | jq .

after_success: bash ./bin/deploy.sh

env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: miya0001@users.noreply.github.com
  - GH_REF: github.com/madefor/static-tile-server
  - secure: "ZnG9pChLWbR4kNFTBGbNxQa9eed1CyCM7J2T57tJONc7ekwEvj6S29lM2LfUnAtf424TVy83K7J9xCxM9rkB6G5YaMo4O+D4XaC8Z8BlBPBMUzZlW4fdui6TOqPYkGhBVO9nqm9roZiyF7yToR8fGxKM82MnSygwYW1D9kF/QSqTNcuOnudYa7IB7eEE2KiADasVnW37ts5lFdqyRpFMjRxHfhDy2W5Zj8+cY4kRGkgD7+DyAeMvOMuw9FM+copuyOp+ldEvJUe7fuLjzcGFCiM9Bp058/Ne1z7Bm3sKaFg+sK2s7X+fF+ZLBQztHQwmrW8b/HfXf2izQfMIbUEIh/xUT2V8+4BL6AZ9xSYtp+wI5T9kOlvkOuykbiZE8XCUe0FbQmLBbqaa6Sr/t9kKI8xLT5b/0mDHwZ6l9vdMS3nxlw3+wxrhF6D0tCP74JvjdvWxMN3pRRBBwiPovRnymYl+NMWyaIfsH3boI2jA28AfAXvOktiIctS9ZST4M4VnHygkNSJbBVFgH3Dpx5wRGzBxAornvx6dGIfaHAOEBx/eK2PbHGKb0D3EHUSnaWb4fU0hLbebnrU6Vz7zxcuMHq07xIu+q4rSVcjvTKUVxX1IZxUdn2sHLS2Xr4YBdwh/vSQCLnGfBImUAsHTySWxmLGoURZPPAUgU7mSJZpJyqE="
